<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4KZXmyk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4KZXmyk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4KZXmyk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4KZXmyk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4KZXmyk\App_KernelDevDebugContainer([
    'container.build_hash' => '4KZXmyk',
    'container.build_id' => 'bab6addc',
    'container.build_time' => 1647265095,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4KZXmyk');
