<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8hmbtb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8hmbtb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY8hmbtb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY8hmbtb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY8hmbtb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y8hmbtb',
    'container.build_id' => 'e1c52bbd',
    'container.build_time' => 1646299122,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8hmbtb');
