<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSDFLDXA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSDFLDXA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSDFLDXA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSDFLDXA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSDFLDXA\App_KernelDevDebugContainer([
    'container.build_hash' => 'SDFLDXA',
    'container.build_id' => 'ee6748b0',
    'container.build_time' => 1646304029,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSDFLDXA');
