<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGnZcxPY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGnZcxPY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGnZcxPY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGnZcxPY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGnZcxPY\App_KernelDevDebugContainer([
    'container.build_hash' => 'GnZcxPY',
    'container.build_id' => 'a593b2c9',
    'container.build_time' => 1652079614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGnZcxPY');
