<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1nMED8B\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1nMED8B/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1nMED8B.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1nMED8B\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1nMED8B\App_KernelDevDebugContainer([
    'container.build_hash' => '1nMED8B',
    'container.build_id' => '4252b1a0',
    'container.build_time' => 1646296809,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1nMED8B');
