<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7rJVGRe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7rJVGRe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7rJVGRe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7rJVGRe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7rJVGRe\App_KernelDevDebugContainer([
    'container.build_hash' => '7rJVGRe',
    'container.build_id' => '00390630',
    'container.build_time' => 1646301863,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7rJVGRe');
